CREATE TABLE COLORS
(
  COLOR_ID INT NOT NULL,
  COLOR_NAME INT NOT NULL,
  PRIMARY KEY (COLOR_ID)
);

CREATE TABLE GARAGE
(
  GARAGE_ID INT NOT NULL,
  GARAGE_LOCATION INT NOT NULL,
  GARAGE_NAME INT NOT NULL,
  PRIMARY KEY (GARAGE_ID)
);

CREATE TABLE COMPANIES
(
  COMPANY_NAME INT NOT NULL,
  COMPANY_ID INT NOT NULL,
  PRIMARY KEY (COMPANY_ID)
);

CREATE TABLE MODELS
(
  MODEL_ID INT NOT NULL,
  MODEL_YEAR INT NOT NULL,
  MODEL_NAME INT NOT NULL,
  COMPANY_ID INT NOT NULL,
  PRIMARY KEY (MODEL_ID),
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(COMPANY_ID)
);

CREATE TABLE CARS_STOCK
(
  CSID INT NOT NULL,
  LICENCE_NUMBER INT NOT NULL,
  MODEL_ID INT NOT NULL,
  BUY_YEAR INT NOT NULL,
  IS_ACTIVE INT NOT NULL,
  CAR_COLOR INT NOT NULL,
  COLOR_ID INT NOT NULL,
  GARAGE_ID INT,
  PRIMARY KEY (CSID),
  FOREIGN KEY (COLOR_ID) REFERENCES COLORS(COLOR_ID),
  FOREIGN KEY (GARAGE_ID) REFERENCES GARAGE(GARAGE_ID),
  FOREIGN KEY (MODEL_ID) REFERENCES MODELS(MODEL_ID),
  UNIQUE (LICENCE_NUMBER)
);