SELECT LICENCE_NUMBER,GARAGE_NAME, GARAGE.GARAGE_LOCATION, GARAGE.GARAGE_PHONE_NUMBER
FROM CARS_STOCK 
LEFT JOIN GARAGE
     ON CARS_STOCK.GARAGE_ID = GARAGE.GARAGE_ID
LEFT JOIN BARKALIF.BRANCH
     ON BARKALIF.BRANCH.ID = CARS_STOCK.BRANCH_ID
WHERE BARKALIF.BRANCH.ID = 15 AND CARS_STOCK.GARAGE_ID IS NOT NULL
