SELECT LICENCE_NUMBER, MODEL_NAME, BARKALIF.BRANCH.ID, BARKALIF.BRANCH.LOCATION, BARKALIF.BRANCH.YEARSTART
FROM CARS_STOCK
LEFT JOIN MODELS
     ON MODELS.MODEL_ID = CARS_STOCK.MODEL_ID
LEFT JOIN COMPANIES
     ON COMPANIES.COMPANY_ID = MODELS.COMPANY_ID
LEFT JOIN BARKALIF.BRANCH
     ON BARKALIF.BRANCH.ID = CARS_STOCK.BRANCH_ID
WHERE COMPANIES.COMPANY_NAME = 'Chevrolet' AND CARS_STOCK.BUY_YEAR >=2021
