SELECT BRANCH.LOCATION,YEARSTART,AMOUNT
FROM (
     SELECT /*+ INDEX (CARS_STOCK CARS_STOCK_BRANCH_ID) */ BRANCH_ID,COUNT(*) AS AMOUNT
     FROM ((SELECT CARS_STOCK.CSID,BRANCH_ID FROM CARS_STOCK)

           MINUS (SELECT CARS_STOCK.CSID,BRANCH_ID FROM TREATMENTS
           LEFT JOIN CARS_STOCK
                ON CARS_STOCK.CSID = TREATMENTS.CSID
           WHERE TREATMENTS.END_DATE>CURRENT_DATE))
           
           GROUP BY BRANCH_ID         
) COUNTED
LEFT JOIN BARKALIF.BRANCH
     ON BARKALIF.BRANCH.ID = COUNTED.BRANCH_ID
