CREATE VIEW COLORED_CARS AS 
SELECT CARS_STOCK.CSID,
       CARS_STOCK.LICENCE_NUMBER,
       CARS_STOCK.MODEL_ID,
       CARS_STOCK.BUY_YEAR,
       COLORS.COLOR_NAME,
       CARS_STOCK.GARAGE_ID,
       CARS_STOCK.BRANCH_ID
 FROM CARS_STOCK
LEFT JOIN  COLORS
     ON COLORS.COLOR_ID = CARS_STOCK.COLOR_ID
