CREATE OR REPLACE VIEW FULL_CARS_DATA AS
SELECT CARS_WITH_MODEL_AND_COMPANY.CSID,
       CARS_WITH_MODEL_AND_COMPANY.LICENCE_NUMBER,
       CARS_WITH_MODEL_AND_COMPANY.MODEL_NAME,
       CARS_WITH_MODEL_AND_COMPANY.COMPANY_NAME,
       CARS_WITH_MODEL_AND_COMPANY.BUY_YEAR,
       BARKALIF.BRANCH.ID,
       BARKALIF.BRANCH.LOCATION,
       BARKALIF.BRANCH.YEARSTART,
       COLORS.COLOR_NAME
 FROM CARS_WITH_MODEL_AND_COMPANY
LEFT JOIN COLORS ON COLORS.COLOR_ID = CARS_WITH_MODEL_AND_COMPANY.COLOR_ID
LEFT JOIN BARKALIF.BRANCH ON BARKALIF.BRANCH.ID = CARS_WITH_MODEL_AND_COMPANY.BRANCH_ID
